---
title: "OHI+ Tetiaroa: Management Resilience"
author: "Maddie Berger"
output:
    html_document:
      highlight: haddock
      includes:
        in_header: '~/github/tet-prep/workflow/templates/tet_hdr.html' 
      number_sections: yes
      theme: cerulean
      toc: yes
      toc_depth: 3
      toc_float: yes
---

# Summary

This script creates the management resilience layer. The methods are identical to the process of calculated the LSP score in the toolbox. 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)

library(tidyverse)
library(here)

source(here('workflow/R/common.R'))

```

# Method 

## Read in data 
```{r}

#read in lsp data 

mgmt_raw <- read_csv(file.path(dir_github, "/prep/resilience/social/management/res_mgmt_raw.csv"))



```



## Calculate "status" score for LSP

```{r}


  land_status <- mgmt_raw %>%
    filter(zone %!in% c("Offshore","No take zone","Rest of lagoon")) %>%
    group_by(year) %>%
    summarize(
      status = weighted.mean(status,area)
    ) #1

  #calculate lagoon scores

  lagoon_status <- mgmt_raw %>%
    filter(zone %in% c("No take zone","Rest of lagoon")) %>%
    group_by(year) %>%
    summarize(
      status = mean(status)
    )

   #offshore, and add the rest to get the final status

  res_mgmt <- mgmt_raw %>%
    filter(zone %in% "Offshore") %>%
    group_by(year) %>%
    summarize(
      status = mean(status)
    ) %>%
    bind_rows(land_status, lagoon_status) %>%
    group_by(year) %>%
    summarize(
      status = mean(status)
    ) %>%
    mutate(
      res_score = status,
      region_id = 1,
      dimension = "status"
    ) %>% 
    dplyr::select(region_id, year, res_score)




```

## Write layers to tool box

```{r}

write_csv(res_mgmt, file.path(dir_github,"/prep/resilience/social/management/res_mgmt.csv"))

write_csv(res_mgmt, file.path(dir_scores, "/region/layers/res_mgmt.csv"))

```

