---
title: 'OHI+ Tetiaroa 2020: Species Diversity Resilience Layer'
author: 'Madeline Berger'
output: 
  html_document:
    highlight: haddock
    includes:
      in_header: '~/github/tet-prep/workflow/templates/tet_hdr.html' 
    number_sections: yes
    theme: cerulean
    toc: yes
    toc_depth: 3
    toc_float: yes
---

# Summary

This script prepares the species diversity resilience layer. It is identical to the methods used to calculate the species diversity status score in the Toolbox.

# Set up 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)

library(here)

source(here('workflow/R/common.R'))
```

# Methods

## Read in final SPP layer from SPP prep 

```{r}

spp_status <- read_csv(file.path(dir_github, "/prep/bd/spp/v2020/output/spp_status.csv"))


```


## Find average scores
```{r}

res_spp_div <- spp_status %>%
   dplyr::filter(year == 2020) %>% #do i need this?
  dplyr::filter(!is.na(status)) %>%
    group_by(region_id, class) %>%
    summarize(
      status = mean(status) #mean per class
    ) %>%
    group_by(region_id) %>%
    summarize(
      res_score = mean(status),
      year = 2020
      #dimension = "status"#average of the 10 classes, final score
    )



```

## Write layer to Toolbox

```{r}

write_csv(res_spp_div, file.path(dir_scores,"/region/layers/res_spp_div.csv"))


```

