---
title: "Creating master rasters"
output: html_document
---
Creating base rasters for data prep 


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#library(tidyverse) #not working idk why
library(sf)
library(raster)
library(fasterize)
library(mapview)
library(utils)
library(here)

source(here('workflow/R/common.R'))

#for updating spatial 

pkgs <- c("sf", "raster", "fasterize")

#projections and crs
p4s_wgs84 <- '+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0'
p4s_nad83 <- '+proj=longlat +ellps=GRS80 +datum=NAD83 +no_defs +towgs84=0,0,0'
azim_eq    <- raster::crs("+proj=laea +lat_1=29.5 +lat_2=45.5 +lat_0=37.5 +lon_0=-96 +x_0=0 +y_0=0 +ellps=GRS80 +datum=NAD83 +units=m +no_defs")

#extents for region of interests - need these for cropping?

wgs_ext <- raster::extent(-149.67, -149.46,-17.10,-16.92)
azim_ext <- raster::extent(-6156061, -6136000,-4607084,-4588580) #this is for equal area projection only

#shapefiles

tet_shp <- tet_buffer_3nm %>% 
  st_transform(crs = azim_eq)  

# tet_shp_sp <- tet_shp %>%
#   as(.,"Spatial") #if you need sp object

land <- tet_motus %>% 
  st_transform(crs = azim_eq)
  # as(., "Spatial") #this natural one is World_Azimuthal_Equidistant whatever that is

plot(azim_ext)
plot(tet_shp, add = T)

mapview(tet_shp) #to find lat lon for extent
```

Create a base raster clipped to the extent
```{r}

#create a base raster with 100x100, crs = wgs84 and tet extent defined above
r <- raster(crs = azim_eq, azim_ext, res = 100)
r[r] <- 1
plot(r)
plot(tet_shp, add = T) #working now
```

Mask out land to create ocean raster
```{r}

all_ras <- mask(r, tet_shp) #this is working now

ocean_ras <- mask(r, land, inverse = T) #working

plot(ocean_ras)
plot(land, add = T) #this is still not working
```

Use fasterize - this is creating the same thing as above with just a different function
```{r}

ras <- fasterize(tet_shp, r)

ras_2 <- fasterize(tet_shp, ocean_ras)

#both these work but not sure how its different than the mask?

```

Write out both rasters
```{r}

writeRaster(ocean_ras, filename = "~/github/tet-prep/spatial/rasters/ocean_ras.tif", overwrite = T)

writeRaster(all_ras, filename = "~/github/tet-prep/spatial/rasters/all_ras.tif", overwrite = T)

```

